# Generated by Django 3.0.3 on 2020-06-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeSite', '0005_auto_20200424_1705'),
        ('users', '0003_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favoritePosts',
            field=models.ManyToManyField(blank=True, null=True, to='recipeSite.Post'),
        ),
    ]
