# Generated by Django 3.0.4 on 2020-04-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='howTo',
            new_name='instructions',
        ),
    ]
