# Generated by Django 3.0.4 on 2020-04-22 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeSite', '0003_auto_20200422_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='instructions',
            new_name='ingredients',
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeSite.Post')),
            ],
        ),
    ]
