# Generated by Django 3.0.3 on 2020-04-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeSite', '0004_auto_20200422_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='Sem descrição', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='logo.png', upload_to='post_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
